name: CI Pipeline

on:
  push:
    branches:
      - main  # Exécute les tests lors d'un push sur la branche principale
  pull_request:
    branches:
      - main  # Exécute les tests lors de la création d'une pull request vers la branche principale

jobs:
  test:
    runs-on: ubuntu-latest  # Utilise une machine virtuelle Ubuntu pour exécuter les tests

    steps:
    # 1. Récupérer le code du dépôt
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurer Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Assurez-vous d'utiliser la version de Python qui correspond à votre projet

    # 3. Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    # 4. Exécuter les tests avec pytest
    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Exécute les tests, en arrêtant après la première erreur (optionnel)
